import http from "node:http";
import pg from "pg";
import { canonicalUrl, completeRecord, extractSourceFacts, fetchOfficial, retryDelayMinutes, safeEqual } from "./candidate.mjs";
const { Pool } = pg;
for (const key of ["DATABASE_URL", "INGEST_TOKEN", "GATE_QUEUE_URL", "GATE_QUEUE_TOKEN"]) if (!process.env[key]) throw new Error(`${key} is required`);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: 6, ssl: process.env.PGSSLMODE === "disable" ? false : undefined });
await pool.query(`CREATE TABLE IF NOT EXISTS gate_candidate_queue (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), url TEXT NOT NULL UNIQUE, title TEXT, snippet TEXT, source TEXT, watch_id TEXT, season TEXT, country TEXT, status TEXT NOT NULL DEFAULT 'discovered', attempt_count INTEGER NOT NULL DEFAULT 0, next_retry_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_error TEXT, gate_record JSONB, discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_attempt_at TIMESTAMPTZ, queued_at TIMESTAMPTZ, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
await pool.query("CREATE INDEX IF NOT EXISTS gate_candidate_ready_idx ON gate_candidate_queue (status, next_retry_at, discovered_at)");
const send = (res, status, body) => { res.writeHead(status, { "content-type": "application/json" }); res.end(JSON.stringify(body)); };
const bearer = (req) => /^Bearer\s+(.+)$/i.exec(req.headers.authorization ?? "")?.[1];
const authorized = (req) => safeEqual(bearer(req), process.env.INGEST_TOKEN);
const readJson = async (req) => { const chunks = []; let bytes = 0; for await (const part of req) { bytes += part.length; if (bytes > 128 * 1024) throw new Error("payload_too_large"); chunks.push(part); } return JSON.parse(Buffer.concat(chunks).toString("utf8")); };
async function extract(posting, row) {
  if (!process.env.OPENAI_API_KEY) return extractSourceFacts(posting, row);
  const prompt = `Extract factual job-posting data as JSON. Never invent. Use null, [], or unknown when absent. Return only keys: company_name,title,normalized_title,track,employment_type,description_summary,location,responsibilities,expected_outcomes,required_skills,preferred_skills,technologies,technical_stack,education,experience_requirements,compensation,eligibility,hiring_process,deadline,materials,match_score,technical_fit,match_reason,satisfies,missing,unknown,recommended_next_action,eligibility_risk,eligibility_risk_reason,assessment_confidence. Technical_stack must separate languages, frameworks, libraries, runtimes, databases, cloud, containers, infrastructure_as_code, ci_cd, observability, testing_tools, security_tools, ai_ml, and developer_tools.\n\nOFFICIAL POSTING:\n${posting.raw.slice(0, 90000)}`;
  const response = await fetch("https://api.openai.com/v1/chat/completions", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: process.env.OPENAI_MODEL || "gpt-4.1-mini", temperature: 0, response_format: { type: "json_object" }, messages: [{ role: "system", content: "You are a precise job-posting extractor." }, { role: "user", content: prompt }] }), signal: AbortSignal.timeout(90_000) });
  if (!response.ok) throw new Error(`openai_http_${response.status}`);
  const body = await response.json(); const content = body.choices?.[0]?.message?.content;
  if (!content) throw new Error("openai_empty_response");
  return JSON.parse(content);
}
async function claim() { const result = await pool.query(`WITH item AS (SELECT id FROM gate_candidate_queue WHERE (((status IN ('discovered','failed') AND next_retry_at <= NOW()) OR (status='processing' AND last_attempt_at < NOW()-INTERVAL '2 minutes')) AND attempt_count < 6) ORDER BY discovered_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE gate_candidate_queue q SET status='processing', attempt_count=q.attempt_count+1, last_attempt_at=NOW(), updated_at=NOW() FROM item WHERE q.id=item.id RETURNING q.*`); return result.rows[0] ?? null; }
async function processOne(row) { try { const posting = await fetchOfficial(row.url); const extracted = await extract(posting, row); const record = completeRecord(row, posting, extracted); const response = await fetch(`${process.env.GATE_QUEUE_URL.replace(/\/+$/, "")}/v1/deliver`, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${process.env.GATE_QUEUE_TOKEN}` }, body: JSON.stringify(record), signal: AbortSignal.timeout(30_000) }); const body = await response.json().catch(() => null); if (response.status !== 202 || !body?.accepted) throw new Error(`queue_http_${response.status}`); await pool.query("UPDATE gate_candidate_queue SET status='queued', gate_record=$2::jsonb, queued_at=NOW(), last_error=NULL, updated_at=NOW() WHERE id=$1", [row.id, JSON.stringify(record)]); console.log(`queued candidate_id=${row.id} extractor=${process.env.OPENAI_API_KEY ? "openai" : "source-only"}`); } catch (error) { const message = String(error?.message ?? error).slice(0, 1000); const terminalByType = /unverified|unsafe|too_short|company_name_not_extracted|title_not_extracted/.test(message); const exhausted = Number(row.attempt_count) >= 6; const terminal = terminalByType || exhausted; await pool.query("UPDATE gate_candidate_queue SET status=$2, last_error=$3, next_retry_at=NOW() + ($4 || ' minutes')::interval, updated_at=NOW() WHERE id=$1", [row.id, terminal ? "skipped" : "failed", message, retryDelayMinutes(row.attempt_count)]); console.warn(`candidate ${terminal ? "skipped" : "failed"} id=${row.id} attempt=${row.attempt_count} error=${message.slice(0,180)}`); } }
let draining = false; async function drain() { if (draining) return; draining = true; try { for (;;) { const row = await claim(); if (!row) return; await processOne(row); } } finally { draining = false; } }
setInterval(() => void drain().catch((error) => console.error("candidate drain failed", error.message)), 15_000); void drain();
const server = http.createServer(async (req, res) => { const path = req.url?.split("?")[0]; if (req.method === "GET" && path === "/health") return send(res, 200, { ok: true, service: "gate-candidate-processor" }); if (!authorized(req)) return send(res, 401, { error: "unauthorized" }); try { if (req.method === "POST" && path === "/v1/candidates") { const body = await readJson(req); const url = canonicalUrl(body.url); if (!/^https:\/\//.test(url)) return send(res, 422, { error: "https_url_required" }); const result = await pool.query("INSERT INTO gate_candidate_queue (url,title,snippet,source,watch_id,season,country,discovered_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(url) DO UPDATE SET updated_at=NOW() RETURNING id,status,url", [url, body.title ?? null, body.content ?? body.snippet ?? null, body.source ?? null, body.watch_id ?? null, body.season ?? "Summer 2027", body.country ?? "US", body.discovered_at ?? new Date().toISOString()]); void drain(); return send(res, 202, { ok: true, candidate: result.rows[0] }); } if (req.method === "GET" && path === "/v1/status") { const result = await pool.query("SELECT status, COUNT(*)::int AS count FROM gate_candidate_queue GROUP BY status ORDER BY status"); return send(res, 200, { ok: true, counts: result.rows }); } return send(res, 404, { error: "not_found" }); } catch (error) { return send(res, 400, { error: String(error?.message ?? error).slice(0, 300) }); } });
const port = Number(process.env.PORT || 3000);
server.listen(port, "0.0.0.0", () => console.log(`GATE candidate processor ready port=${port}`));
